# Generated by Django 4.2.16 on 2024-09-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('uuid_portal', models.UUIDField(editable=False, unique=True, verbose_name='UUID no Portal')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição da categoria de entidades')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('uuid_portal', models.UUIDField(editable=False, unique=True, verbose_name='UUID no Portal')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do tipo de entidade')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição do tipo')),
            ],
            options={
                'verbose_name': 'Hierarquia Organizacional',
                'verbose_name_plural': 'Hierarquias Organizacionais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da entidade')),
                ('code', models.CharField(default=0, max_length=10, verbose_name='Código da Entidade no EM8')),
                ('uuid_portal', models.UUIDField(blank=True, null=True, verbose_name='UUID no Portal')),
                ('dad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.entity', verbose_name='Entidade superior')),
                ('gender', models.ManyToManyField(blank=True, related_name='entity', to='portal.gender', verbose_name='Categoria')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.organizationalhierarchy', verbose_name='Hierarquia')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enjoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nome de usuário')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Último nome')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('phone', models.CharField(blank=True, max_length=36, null=True, verbose_name='Número de telefone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='enjoyers', verbose_name='Image')),
                ('uuid_portal', models.UUIDField(blank=True, null=True, verbose_name='UUID no Portal')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_enjoyer', to='portal.entity')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enjoyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
            },
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('rank', models.CharField(blank=True, max_length=36, null=True, verbose_name='Patente')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nome completo')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de guerra')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('register', models.CharField(blank=True, max_length=7, null=True, verbose_name='Matricula')),
                ('activity_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Regime')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('father', models.CharField(blank=True, max_length=256, null=True, verbose_name='Pai')),
                ('mather', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mãe')),
                ('place_of_birth', models.CharField(blank=True, max_length=64, null=True, verbose_name='Naturalidade')),
                ('marital_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado Civil')),
                ('phone', models.CharField(blank=True, max_length=36, null=True, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, default='S/N', max_length=16, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('zipcode', localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('military_identity', models.CharField(blank=True, max_length=36, null=True, verbose_name='Identidade Militar')),
                ('cnh', models.CharField(blank=True, max_length=36, null=True, verbose_name='Carteira de Motorista')),
                ('rg', models.CharField(blank=True, max_length=36, null=True, verbose_name='Registro Geral')),
                ('orgao_expeditor_rg', models.CharField(blank=True, max_length=16, null=True, verbose_name='Órgão Expeditor')),
                ('uuid_portal', models.UUIDField(blank=True, null=True, verbose_name='UUID no Portal')),
                ('image', models.ImageField(blank=True, null=True, upload_to='militaries_pmpb', verbose_name='Image')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='military', to='portal.entity')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='military', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policial Militar',
                'verbose_name_plural': 'Policiais Militares',
                'unique_together': {('register', 'cpf')},
            },
        ),
    ]
