# Generated by Django 5.0.1 on 2024-01-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExemploImagens',
        ),
    ]
