# Generated by Django 4.2.16 on 2025-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criminoso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcriminoso",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
