# Generated by Django 4.2.23 on 2025-06-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0002_cardcriminoso_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cardcriminoso',
            name='crime',
            field=models.CharField(choices=[('ASSALTO', 'Assalto'), ('ESTUPRO', 'Estupro'), ('FURTO', 'Furto'), ('MAO_ARMADA', 'Mão Armada')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardcriminoso',
            name='faccao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criminosos', to='criminoso.faccao'),
        ),
    ]
