# Generated by Django 4.2.16 on 2025-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0002_cardcriminoso_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcriminoso',
            name='recompensa',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$'), ('$$$$$', '$$$$$')], default='$', max_length=5),
        ),
    ]
