# Generated by Django 4.2.23 on 2025-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0003_faccao_alter_cardcriminoso_crime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcriminoso',
            name='faccao',
            field=models.CharField(choices=[('OKAIDA', 'Okaida'), ('COMANDO VERMELHO', 'Comando Vermelho (CV)'), ('PRIMEIRO COMANDO DA CAPITAL', 'Primeiro Comando da Capital (PCC)')], default='OKAIDA', max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Faccao',
        ),
    ]
