# Generated by Django 4.2.16 on 2025-06-17 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0003_alter_cardcriminoso_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcriminoso',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cardcriminoso',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardcriminoso',
            name='validade',
            field=models.IntegerField(choices=[(15, '15 dias'), (30, '30 dias'), (60, '60 dias'), (90, '90 dias')], default=30),
        ),
    ]
