# Generated by Django 4.2.16 on 2025-07-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0004_alter_cardcriminoso_faccao_delete_faccao'),
        ('criminoso', '0004_cardcriminoso_atualizado_em_cardcriminoso_criado_em_and_more'),
    ]

    operations = [
    ]
