# Generated by Django 4.2.16 on 2025-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0005_merge_20250716_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcriminoso',
            name='faccao',
            field=models.CharField(choices=[('OKAIDA', 'Okaida'), ('COMANDO VERMELHO', 'Comando Vermelho (CV)'), ('PCC', 'Primeiro Comando da Capital (PCC)'), ('ADA', 'Amigos dos Amigos'), ('TCP', 'Terceiro Comando'), ('CN', 'Comando Nordeste'), ('EUA', 'Estados Unidos')], max_length=40),
        ),
        migrations.AlterField(
            model_name='cardcriminoso',
            name='recompensa',
            field=models.IntegerField(),
        ),
    ]
