# Generated by Django 4.2.16 on 2025-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminoso', '0006_alter_cardcriminoso_faccao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcriminoso',
            name='recompensa',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$'), ('$$$$$', '$$$$$')], default='$', max_length=5),
        ),
    ]
